### ISSUE TITLE
Протестировать алгоритм на датасете 

### ISSUE THREAD

**Issue by margofurman** [citec-spbu/Auto-Color-Correction#10]
- [ ] Прогнать по 10 картинок из датасетов Night и Foggy night, посмотреть на результат, оценить эмпирически 
- [ ] Проверить, не изменяется ли размер картинки и глубина цвета после скачивания

**Comment by IvanEfremovSPBU** [comment]
Среднее время обработки при WINDOW_SIZE = 7 и размере изображения в пределах fullHD на NVidia 3070:  62,6ms, что примерно равняется 1/15 секунды.
