### ISSUE TITLE
Ревью script.js

### ISSUE THREAD

**Issue by margofurman** [citec-spbu/Auto-Color-Correction#19]
Найти причину ошибки двойного клика

**Comment by Darnelo-Inc** [comment]
Проблема возникает из-за разрыва в последовательности загрузки изображения и последующей отрисовки в видимом processedCanvas. Если изображения загружаются асинхронно, обработка может завершиться не сразу, что приводит к необходимости повторного нажатия.

Исправлю это, изменив структуру кода, чтобы удостовериться, что изображение полностью загружено и отрисовано в скрытом textureCanvas перед тем, как его использовать для отрисовки в processedCanvas.
