### ISSUE TITLE
Автоматизация тестирования

### ISSUE THREAD

**Issue by IvanEfremovSPBU** [citec-spbu/Auto-Color-Correction#24]
**Требуемый функционал:**
Автоматизированное тестирование алгоритма на массиве изображений или видео и сбор статистики (время, значение параметров, значение метрики цветового различия).
**Входные данные:**
Исходные данные в виде массивов изображений или видео

**Comment by Apophis142** [comment]
Реализован перебор всех картинок из директории (на любой глубине) итоговая картинка после работы алгоритма берется [отсюда](https://citec-spbu.github.io/Auto-Color-Correction/). Можно проверить алгоритм после его добавления в основную ветку. В файл будет вестись запись абсолютных путей входного и выходного изображения, а также время работы, если оно было измерено. Время следует выводить на сайте в каком-нибудь блоке с id `spentTime`.
