### ISSUE TITLE
Изменяется размер картинки при выводе

### ISSUE THREAD

**Issue by margofurman** [citec-spbu/Auto-Color-Correction#3]

**Comment by margofurman** [comment]
Размер картинки и глубина цветом меняются после загрузки на страничку

**Comment by IvanEfremovSPBU** [comment]
**Описание**
При загрузке изображения на веб страницу не сохраняется изначальное разрешение, соотношение сторон и глубина цвета, из-за чего обработанное изображение не совпадает с оригинальным. Проблема с разрешением и соотношением сторон возникает из-за того, что размер изображения превышает максимальные фиксированные размеры элементов canvas.
**Ожидаемое поведение**
Изображение загружается на страницу и если его размер не совпадает с максимальными размерами canvas, то оно масштабируется до нужного размера, сохраняя соотношение сторон. При этом сохраняется изначальная глубина цвета.
