### ISSUE TITLE
Создать тестовый датасет из изображений

### ISSUE THREAD

**Issue by IvanEfremovSPBU** [citec-spbu/Auto-Color-Correction#9]
- [x] **Подбор изображений с различными характеристиками для референсного набора:**
- Изображения в различных разрешениях: 176x144 (QCIF), 640x480 (VGA), 1920x1080 (HD), 3840×2160 (UHD 4K)
- Изображения в различных цветовых тонах: черно-белые, одноцветные (большая часть картинки зелёная/красная/синяя), с большим количеством цветов
- [x] **Обработка изображений для создания различных дефектов:**
- Высокая/низкая контрастность
- Преобразование палитры цветов в ночную для дневных изображений/в дневную для ночных
- Преобразование палитры цветов в более тёплую/холодную
- [x] **Обработка дополнительными дефектами**
- Высокий уровень шума
- Сильное размытие

**Comment by Apophis142** [comment]
Добавлено 16+18 изображений с разрешением 640x480, полученные преобразованием дневных изображений в ночные. Уровень шума на картинке неоднородный.

**Comment by margofurman** [comment]
Различные характеристики:
по 5 штук каждой группы размер 176x144 (QCIF), 640x480 (VGA), 1920x1080 (HD), 3840×2160 (UHD 4K) для каждой цветовой категории - чб, преимущественно одноцветные, многоцветные
